$ ->
        c = SW.card.create()
        c.set('section', "field")
        c.set('position', [0,1])
        c.set('side', 1)
        c.set('fraction', 'Cave Goblins')
        c.set('name', 'Fighter')
        d = SW.card.create()
        d.set('section', "field")
        d.set('position', [5,5])
        d.set('side', 0)
        d.set('fraction', 'Mercenaries')
        d.set('name', 'Owl Familiar')
        e = SW.card.create()
        e.set('section', "field")
        e.set('position', [1,1])
        e.set('side', 0)
        e.set('name', 'Lun')
        e.set('fraction', 'Deep Dwarves')
        e = SW.card.create()
        e.set('section', "hand")
        e.set('side', 0)
        e.set('name', 'Scholar')
        e.set('fraction', 'Deep Dwarves')
        f = SW.card.create()
        f.set('section', "hand")
        f.set('side', 0)
        f.set('name', 'Miner')
        f.set('fraction', 'Deep Dwarves')